// <auto-generated />
namespace TestTask.Shortener.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0001_Initialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0001_Initialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201706112325320_0001_Initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
